//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPMS.DAL
{
    using PPMS.ENTITIES;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppmsEntities : DbContext
    {
        public ppmsEntities()
            : base("name=ppmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<DailyCashSaleDenomination> DailyCashSaleDenominations { get; set; }
        public virtual DbSet<DailyFuelCost> DailyFuelCosts { get; set; }
        public virtual DbSet<DailyMeterReading> DailyMeterReadings { get; set; }
        public virtual DbSet<DailyTankerReading> DailyTankerReadings { get; set; }
        public virtual DbSet<DenominationType> DenominationTypes { get; set; }
        public virtual DbSet<Fuel> Fuels { get; set; }
        public virtual DbSet<Meter> Meters { get; set; }
        public virtual DbSet<OperationMaster> OperationMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<RoleOperationMapping> RoleOperationMappings { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Tanker> Tankers { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
    }
}
